### ISSUE TITLE
How to run forecasting task.

### ISSUE THREAD

**Issue by vermabasu** [AI4HealthUOL/SSSD-ECG#11]
Hi, I'm trying to run the forecasting task on PTB-XL (248) dataset. Can you clarify what all changes need to do to run forecasting task? I have tried all the previous solution mentioned in closed issues but getting errors. Also, while inference, what is the purpose of "number of utterance to be generated" argument?

**Comment by juanlopezcode** [comment]
Hi, I believe it is about SSSD model itself rather than this ecg application. The forecasting task is a blackout scenario, using mask iteratively sampled at different time steps windows per batch during training, and the --num-samples argument is about how many batch sizes while generating/imputing.
